# Generated by Django 4.2.7 on 2024-01-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='payment_time',
        ),
        migrations.AddField(
            model_name='prescription',
            name='instruction',
            field=models.TextField(null=True),
        ),
    ]
