# Generated by Django 4.2.7 on 2024-01-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_prescription_payment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
    ]
