# Generated by Django 4.2.7 on 2024-01-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_prescription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(default=3, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
