# Generated by Django 4.2.7 on 2024-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_membership_type_alter_payment_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(default=3, max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
