# Generated by Django 4.2.7 on 2024-01-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_desscription_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='total_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='total_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='total_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='total_payment',
            field=models.IntegerField(default=0),
        ),
    ]
