# Generated by Django 4.2.7 on 2024-01-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_post_lastbooking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lastbooking_date',
        ),
        migrations.AddField(
            model_name='service',
            name='lastbooking_date',
            field=models.DateField(null=True),
        ),
    ]
