# Generated by Django 4.2.7 on 2024-01-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_post_lastbooking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
